//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expenses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int Id { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public decimal ExpenseAmount { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string UserCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string UserModified { get; set; }
    }
}
